apiVersion: v1
kind: Config
clusters:
- name: default
  cluster:
    server: https://kubernetes.default.svc
    insecure-skip-tls-verify: true
contexts:
- name: default
  context:
    cluster: default
    namespace: default
current-context: default
preferences: {}
users: []