apiVersion: v1
kind: Service
metadata:
  name: k8s-mcp
  labels:
    app: k8s-mcp
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: k8s-mcp 